from __future__ import annotations

import hashlib
import json
from pathlib import Path

from chemagent_qsm.schema import WorkflowPlan


def generate_python_workflow(plan: WorkflowPlan, path: Path) -> Path:
    """Emit a rerunnable Python workflow whose source contains a plan checksum.

    The generated script is intentionally small and auditable: it does not contain hidden
    model calls, shell calls, or dynamic imports beyond the ChemAgent-QSM orchestrator. The
    full scientific workflow is serialized as normalized JSON and validated again at run time.
    """
    payload = json.dumps(plan.to_yamlable(), indent=2, sort_keys=True)
    plan_sha256 = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    code = (
        "#!/usr/bin/env python\n"
        "# Generated by ChemAgent-QSM.\n"
        "# This file is auditable: the normalized WorkflowPlan JSON below is the only source of\n"
        "# scientific instructions, and it is validated before execution.\n"
        f"# plan_sha256={plan_sha256}\n\n"
        "from chemagent_qsm.orchestrator import ChemAgentQSM\n"
        "from chemagent_qsm.schema import WorkflowPlan\n\n"
        f"PLAN_JSON = {payload!r}\n"
        f"EXPECTED_PLAN_SHA256 = {plan_sha256!r}\n\n"
        "def main():\n"
        "    import hashlib\n"
        "    digest = hashlib.sha256(PLAN_JSON.encode('utf-8')).hexdigest()\n"
        "    if digest != EXPECTED_PLAN_SHA256:\n"
        "        raise RuntimeError('Workflow plan checksum mismatch.')\n"
        "    plan = WorkflowPlan.model_validate_json(PLAN_JSON)\n"
        "    result = ChemAgentQSM().run(plan)\n"
        "    print('Workflow complete:', result['output_dir'])\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(code, encoding="utf-8")
    path.chmod(0o755)
    return path
