from __future__ import annotations

from pathlib import Path

from chemagent_qsm.exceptions import OptionalDependencyError
from chemagent_qsm.schema import MoleculeSpec


def read_xyz(path: Path) -> str:
    lines = Path(path).read_text(encoding="utf-8").strip().splitlines()
    if not lines:
        raise ValueError(f"Empty XYZ file: {path}")
    if len(lines) >= 3 and lines[0].strip().isdigit():
        return "\n".join(lines[2:])
    return "\n".join(lines)


def write_xyz(atom_block: str, path: Path, comment: str = "generated by ChemAgent-QSM") -> None:
    atoms = [ln for ln in atom_block.strip().splitlines() if ln.strip()]
    body = "\n".join(atoms)
    Path(path).write_text(f"{len(atoms)}\n{comment}\n{body}\n", encoding="utf-8")


def atom_block_from_spec(spec: MoleculeSpec) -> str:
    if spec.atom_block:
        return spec.atom_block.strip()
    if spec.xyz_path:
        return read_xyz(spec.xyz_path)
    if spec.smiles:
        return atom_block_from_smiles(spec.smiles)
    raise ValueError("MoleculeSpec has no structure.")


def atom_block_from_smiles(smiles: str, seed: int = 17) -> str:
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem
    except Exception as exc:
        raise OptionalDependencyError(
            "RDKit is required to build 3D coordinates from SMILES. Install chemagent-qsm[qm] "
            "or provide atom_block/xyz_path."
        ) from exc

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES: {smiles}")
    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = seed
    status = AllChem.EmbedMolecule(mol, params)
    if status != 0:
        raise ValueError(f"RDKit embedding failed for SMILES: {smiles}")
    AllChem.UFFOptimizeMolecule(mol, maxIters=500)
    conf = mol.GetConformer()
    lines = []
    for atom in mol.GetAtoms():
        pos = conf.GetAtomPosition(atom.GetIdx())
        lines.append(f"{atom.GetSymbol()} {pos.x:.8f} {pos.y:.8f} {pos.z:.8f}")
    return "\n".join(lines)


def parse_atom_block(atom_block: str) -> list[tuple[str, float, float, float]]:
    atoms: list[tuple[str, float, float, float]] = []
    for line in atom_block.strip().splitlines():
        if not line.strip():
            continue
        parts = line.replace(",", " ").split()
        if len(parts) < 4:
            raise ValueError(f"Invalid atom line: {line!r}")
        atoms.append((parts[0], float(parts[1]), float(parts[2]), float(parts[3])))
    return atoms
